version: "3"

services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    env_file: .env
    restart: always

  mysql:
    image: mysql:5.7
    platform: linux/x86_64 # for Apple Silicon
    ports:
      - "3307:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    env_file: .env
    restart: always

volumes:
  db_mysql:
