#!/bin/bash
set -Ceux

case $1 in
  "init")
    cp example.env .env
  ;;
  "up")
    docker compose up
  ;;
  "down")
    docker compose down
  ;;
  "reset")
    docker compose down && \
    docker compose up
  ;;
  *)
    echo Unexpected command.
  ;;
esac
